// ADDON: saas-mt — One-time claim tokens for Lynk.id integration
import crypto from "node:crypto";
import { getAdapter } from "../driver.js";
import { createRedeemCodes } from "./redeemCodesRepo.js";

function generateToken() {
  return crypto.randomBytes(16).toString("base64url"); // 22 chars, URL-safe
}

/**
 * Generate batch of claim tokens.
 */
export async function createClaimTokens({
  count = 1,
  plan = "free",
  durationDays = 3,
  quotaDailyLimit = 300,
  quotaMonthlyLimit = 9000,
  maxClaims = 1,
  label = null,
  expiresAt = null,
} = {}) {
  const db = await getAdapter();
  const tokens = [];
  for (let i = 0; i < count; i++) {
    const token = generateToken();
    db.run(
      `INSERT INTO claimTokens (token, plan, durationDays, quotaDailyLimit, quotaMonthlyLimit, maxClaims, isActive, label, expiresAt)
       VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)`,
      [token, plan, durationDays, quotaDailyLimit, quotaMonthlyLimit, maxClaims, label, expiresAt]
    );
    tokens.push({ token, plan, durationDays, quotaDailyLimit, quotaMonthlyLimit, maxClaims, label });
  }
  return tokens;
}

/**
 * Claim a token: validate, generate redeem code, increment counter.
 * Returns { code, plan, ... } on success, { error } on failure.
 */
export async function claimToken(token, email) {
  if (!token) return { error: "Token required" };
  if (!email) return { error: "Email required" };
  const db = await getAdapter();
  const row = db.get(`SELECT * FROM claimTokens WHERE token = ?`, [token]);
  if (!row) return { error: "Invalid link" };
  if (!row.isActive) return { error: "Link sudah tidak aktif" };
  if (row.claimedCount >= row.maxClaims) return { error: "Stok habis" };
  if (row.expiresAt && new Date(row.expiresAt) < new Date()) return { error: "Link expired" };

  // Check duplicate claim by email
  const alreadyClaimed = await hasAlreadyClaimed(row.id, email);
  if (alreadyClaimed) return { error: "Email ini sudah pernah claim. Satu email hanya bisa claim 1 kali." };

  // Generate a redeem code
  const [code] = await createRedeemCodes({
    count: 1,
    plan: row.plan,
    durationDays: row.durationDays,
    quotaDailyLimit: row.quotaDailyLimit,
    quotaMonthlyLimit: row.quotaMonthlyLimit,
    maxUses: 1,
    label: `claim:${token.slice(0, 8)}`,
  });

  // Log claim + increment count
  await logClaim(row.id, email);
  db.run(`UPDATE claimTokens SET claimedCount = claimedCount + 1 WHERE id = ?`, [row.id]);

  return {
    success: true,
    code: code.code,
    plan: row.plan,
    durationDays: row.durationDays,
  };
}

/**
 * List all claim tokens (admin).
 */
export async function listClaimTokens({ limit = 100, offset = 0 } = {}) {
  const db = await getAdapter();
  return db.all(
    `SELECT * FROM claimTokens ORDER BY createdAt DESC LIMIT ? OFFSET ?`,
    [limit, offset]
  );
}

/**
 * Deactivate a claim token.
 */
export async function deactivateClaimToken(id) {
  const db = await getAdapter();
  db.run(`UPDATE claimTokens SET isActive = 0 WHERE id = ?`, [id]);
}

/**
 * Delete a claim token permanently.
 */
export async function deleteClaimToken(id) {
  const db = await getAdapter();
  db.run(`DELETE FROM claimTokens WHERE id = ?`, [id]);
}

/**
 * Check if email/phone already claimed this token.
 */
export async function hasAlreadyClaimed(tokenId, email) {
  const db = await getAdapter();
  // Check redeemCodes generated by this token that were used by this email
  const row = db.get(
    `SELECT rc.id FROM redeemCodes rc
     INNER JOIN customers c ON c.email = ?
     WHERE rc.label LIKE ? AND rc.usedCount > 0
     LIMIT 1`,
    [email.toLowerCase().trim(), `claim:%`]
  );
  // Also check claimLog
  const logRow = db.get(
    `SELECT id FROM claimLog WHERE tokenId = ? AND LOWER(email) = ?`,
    [tokenId, email.toLowerCase().trim()]
  );
  return !!(row || logRow);
}

/**
 * Log a claim (email + token) for duplicate detection.
 */
export async function logClaim(tokenId, email) {
  const db = await getAdapter();
  db.exec(`CREATE TABLE IF NOT EXISTS claimLog (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tokenId INTEGER NOT NULL,
    email TEXT NOT NULL,
    claimedAt TEXT NOT NULL DEFAULT (datetime('now'))
  )`);
  db.exec(`CREATE INDEX IF NOT EXISTS idx_cl_token_email ON claimLog(tokenId, email)`);
  db.run(`INSERT INTO claimLog (tokenId, email) VALUES (?, ?)`, [tokenId, email.toLowerCase().trim()]);
}
